name = "Nicro"
license = "MIT"
licenselink = "https://github.com/nicr9/nicro/blob/master/LICENSE"
description = "A minimalist Hugo theme for blog.nicro.land"
homepage = "https://blog.nicro.land"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
]
features = [
  "accessibility",
  "algolia",
  "analytics",
  "breadcrumbs",
  "comments",
  "cover-image",
  "disqus",
  "entry-navigation",
  "favicon",
  "fuse.js",
  "isso",
  "lunr.js",
  "multilingual",
  "multi-author",
  "opengraph",
  "pagination",
  "rtl",
  "search",
  "shortcodes",
  "sidebar",
  "single-column",
  "social-menu",
  "staticman",
  "syntax-highlighting",
  "table-of-contents",
  "utterances",
  "widgets"
]

[author]
  name = "Nic Roland"
  homepage = "https://blog.nicro.land"
